### ISSUE TITLE
Disable https urlbar highlighting

### ISSUE THREAD

**Issue by trondsg** [Exalm/gnomerunner#11]
Thanks for making this theme. Can you make an option so that the url bar doesn't get highlighted with https? So many sites are https these days, and the yellow tooltip colour doesn't blend in right.

**Comment by Exalm** [comment]
There is a builtin SM option for that.

**Comment by trondsg** [comment]
I don't know what SM is, but I can only find the option "alternative hightlight colours" which doesn't turn off the color. In the extension "GNOMErunner Options" 0.4.1.

**Comment by Exalm** [comment]
SM is SeaMonkey. Preferences -> Browser -> Location Bar -> Highlight web pages with a high level of connection security

**Comment by trondsg** [comment]
Thanks, that solved it. Sorry to bother you.
