### ISSUE TITLE
SeaMonkey 2.49.1 can't send mails (and other issues)

### ISSUE THREAD

**Issue by Sammyboy** [Exalm/gnomerunner#12]
I tested it on Slackware 14.2 with SeaMonkey 2.49.1 and GNOMErunner 0.4.4:

- When I "Compose" a new mail and click on the "Send" button or press Ctrl+Enter, the "HTML Question" popup window appears, then I click "Send", it disappears, but nothing else happens and the "Compose" windows does not close. The mail isn't being sent.

- When I click the "Save" button, a new draft is being created, but the "Compose" window doesn't close. And if I close it manually, it asks me whether to save the Mail, even if there's no change after pressing "Save".
 
- When I open the draft for editing it, the "To:" field and the message content are wiped.

**Comment by Exalm** [comment]
Does it work without the theme?

**Comment by Sammyboy** [comment]
Yes, after switching to "SeaMonkey Default Theme", "SeaMonkey Modern" or "SeaMonkey Gray Modern" it works.

**Comment by Exalm** [comment]
Ok, thanks

**Comment by Exalm** [comment]
Yes, I can confirm this. Modern2 and xpfe-classic are also affected.
No idea what could be the reason though, I don't see any recent changes in https://github.com/mozilla/releases-comm-central/commits/master/suite/themes that could cause this.

**Comment by Exalm** [comment]
I meant the changes in the default themes that fix this problem.

**Comment by dilworks** [comment]
Apparently this affects other themes, like Classic Firefox 2 (which is actually not compatible with SM2.49+, but works fine if version checks are turned off aside of this email composer issue)

**Comment by Exalm** [comment]
https://github.com/Exalm/gnomerunner/commit/893743f7b1f9c9d97c671e63bf089eb0b7160e8c

**Comment by OnkelHim** [comment]
Another problem with SM 2.49.1 and xpfe-classic is that the focus is not in the address-field of the new message window when it is opened.

**Comment by Exalm** [comment]
With the new version?

**Comment by Sammyboy** [comment]
> the focus is not in the address-field of the new message window
I can't confirm that. Works fine here.
